### ISSUE TITLE
Issue with installing infirmary-integrated on MacBook Air M1 - Assistance needed (Beginner)

### ISSUE THREAD

**Issue by jney72** [tanjera/infirmary-integrated#198]
Hello, I have a MacBook Air M1, and as a beginner in programming and installation, I'm facing difficulties installing infirmary-integrated. I have tried nearly all available versions, including holding down the Control key during installation and adjusting the Mac's security settings. However, the infirmary-integrated icon appears in the dock for a few seconds and then disappears. I would greatly appreciate it if someone could provide assistance with this matter.

**Comment by jney72** [comment]
![image](https://github.com/tanjera/infirmary-integrated/assets/138227073/83e05182-f77c-43a2-ba6c-7d24f872b33d)

**Comment by tanjera** [comment]
Hi! I'm going to start a discussion and tag your name and also leave the link here so I can help you troubleshoot installing. I just want to close out the GitHub issue because issues are how I track bugs and feature requests. Moving the topic to https://github.com/tanjera/infirmary-integrated/discussions/199
