### ISSUE TITLE
Missing "Access.cs" class

### ISSUE THREAD

**Issue by Frogman7** [tanjera/infirmary-integrated#85]
Couldn't compile project due to the "Access.cs" file located in the project "II Core" being missing.

**Comment by tanjera** [comment]
This is intentional. Access.cs has the username, password, and database information for the runtime mirroring database. It isn't pushed to Github to prevent sharing passwords publicly. It is stored password protected in Access.rar. You can copy [Access Examples](https://github.com/tanjera/infirmary-integrated/blob/master/II%20Core/Classes/Access%20Example.cs) into a new Access.cs for it to compile.

**Comment by tanjera** [comment]
Also note that data in save files is encrypted with a key stored in Access.cs, which is not shared publicly. So save files or scenario files will not be interchangeable between three public build and private builds.
